version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: order-validation-api
    container_name: order-validation-api-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
